<a href="https://colab.research.google.com/github/NinaNikolova/data_mining/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.ones([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = np.zeros([3])
arr

array([0., 0., 0.])

In [ ]:
arr = np.array([[3,2,1],[4,4,4]])
arr

array([[3, 2, 1],
       [4, 4, 4]])

In [ ]:
arr = np.random.rand(5,4)
arr

array([[0.21767037, 0.30876272, 0.23665565, 0.22772998],
       [0.27502347, 0.80385029, 0.6612486 , 0.35837516],
       [0.79861767, 0.62064816, 0.89286678, 0.13262157],
       [0.70996703, 0.72371717, 0.21330802, 0.93543059],
       [0.35212825, 0.61669528, 0.4121754 , 0.22525319]])

In [ ]:
arr = np.array([[1,2],[5,4]], dtype=np.float)
arr

array([[1., 2.],
       [5., 4.]])

In [ ]:
arr = np.array([[1,2],[5,4]], dtype=np.float)
print(arr.dtype)
print(arr.shape)

float64
(2, 2)


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])

np.matmul(arr1, arr2)

array([14, 32])

In [ ]:
arr1 = arr1.T

arr1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.matmul(arr1,arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
arr2 = np.array([1,2])

np.matmul(arr1,arr2)

array([ 9, 12, 15])

In [ ]:
arr2.shape

(2,)

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
np.matmul(arr1,arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
np.exp(arr1)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
arr1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
arr1.reshape(1,7)

ValueError: cannot reshape array of size 6 into shape (1,7)

In [ ]:
arr1.dtype

dtype('int32')

In [ ]:
arr1.astype(np.int)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [ ]:
import time

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print('Vectorized', 1000*(toc-tic), 'ms')

c = 0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()

print(c)
print('For loop', 1000*(toc-tic), 'ms')

250240.0101713515
Vectorized 2.002239227294922 ms
250240.0101713518
For loop 612.6494407653809 ms


In [ ]:
arr1 = np.ones((3,3))

arr2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
print('Columns: Apples, Beef, Eggs, Potatoes')
print('Rows: Carb, protein, fat')

Columns: Apples, Beef, Eggs, Potatoes
Rows: Carb, protein, fat


In [ ]:
A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [ ]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [ ]:
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
